sudo: required

env:
  global:
    - CCACHE_DIR=${HOME}/.ccache
    - CATKIN_BUILD="mkdir -p ~/catkin_ws/src; cd ~/catkin_ws; ln -s ${TRAVIS_BUILD_DIR} src/px4_msgs; catkin build"
    - COLCON_BUILD="mkdir -p ~/colcon_ws/src; cd ~/colcon_ws; ln -s ${TRAVIS_BUILD_DIR} src/px4_msgs; colcon build --cmake-args --symlink-install --event-handlers console_direct+"

matrix:
  include:
    - name: Build on ROS2 Ardent
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS1_DISTRO=kinetic
        - ROS2_DISTRO=ardent
        - ROS1_ENV=/opt/ros/${ROS1_DISTRO}/setup.bash
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-ardent:2019-06-27
    - name: Build on ROS2 Bouncy
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS1_DISTRO=melodic
        - ROS2_DISTRO=bouncy
        - ROS1_ENV=/opt/ros/${ROS1_DISTRO}/setup.bash
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-bouncy:2019-06-27
    - name: Build on ROS2 Crystal
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS1_DISTRO=melodic
        - ROS2_DISTRO=crystal
        - ROS1_ENV=/opt/ros/${ROS1_DISTRO}/setup.bash
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-crystal:2019-06-27

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker run -it --rm -w ${TRAVIS_BUILD_DIR} --env=CCACHE_DIR="${CCACHE_DIR}" --env=LOCAL_USER_ID="$(id -u)" --volume=${CCACHE_DIR}:${CCACHE_DIR}:rw --volume=${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}:rw ${DOCKER_CONTAINER} /bin/bash -c "source ${ROS2_ENV}; ${COLCON_BUILD}"; fi
  - if [ "$TRAVIS_BRANCH" = "ros1" ]; then docker run -it --rm -w ${TRAVIS_BUILD_DIR} --env=CCACHE_DIR="${CCACHE_DIR}" --env=LOCAL_USER_ID="$(id -u)" --volume=${CCACHE_DIR}:${CCACHE_DIR}:rw --volume=${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}:rw ${DOCKER_CONTAINER} /bin/bash -c "source ${ROS1_ENV}; ${CATKIN_BUILD}"; fi
